theme = "hugo-theme-shell"
baseURL = 'https://johncoronel.dev/'
languageCode = 'en-us'
title = 'John Coronel'
[Params]
    custom_css = ["css/custom.css"]
[Params.Terminal]
schema = "monokai"
userName = "John"
pcName = "laptop"
workDir = "home"
profile = "profile.json"
terminalDelay = 3
activityDelay = 2

description = "/description.md"
 [Params.Tree]
  use = true
folderName = "links"
files = [["LinkedIn", "https://www.linkedin.com/in/john-m-coronel/"]]


[module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"